### ISSUE TITLE
update DNA file to support Kalliope v0.5.0

### ISSUE THREAD

**Issue by Sispheor** [bacardi55/kalliope-mpd#2]
We've update the major release of Kalliope to v0.5.0 due to the breaking changes we made by adding hook feature.
You just need to add the new tag to your DNA file [like here](https://github.com/kalliope-project/kalliope_neuron_slack/commit/f76d829e7fd3ad95f8adb2ea7045b7ea2c859584).

**Comment by bacardi55** [comment]
Done in commit f7e0c10b6cb771f769f2d696434ba75a07445de0, thanks
